config/routes.rb
Rails.application.routes.draw do
  # resources :gardens  => all seven routes

  # When you start to think about nesting a route
  # ask yourself if you need the :parent_resource_id.
  # Are your models associated? Do they have a relationship?
  # If so, go ahead without fear! You probably need it.

  # The main reason to nest your route is when we have a belongs_to/has_many relationship.
  # In this case, you probably need a nested route. Why?

  # When you create the child instance, YOU MUST assign a parent to it.
  # Said so, you will need to be able to associate those instances
  # in the create action inside the respective controller.
  # general_example: child_instance.parent = parent
  # real_example: review.restaurant = restaurant

  # So, in the belongs_to/has_many relationship
  # WE MUST NEST THE CHILD INTO THE PARENT
  # This is what happens in our `Gardens & Plants` app and
  # in our `Restaurant & Reviews`

  # Keep in mind that we should avoid nested routes.
  # They are easy to do but can get very hard to work with.
  # Only use when necessary.

  resources :gardens, only: :show do
    resources :plants, only: :create
  end

  # To destroy an instance of any class
  # We only need to know the id and voi la
  resources :plants, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy # => what would happen with the "orphan" plants

  validates :name, :banner_url, presence: true
  validates :name, length: { minimum: 3 }
  validates :banner_url, format: { with: /\Ahttp.+\.(jpg|png)/ }
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  # We want to display the new plant form in the show view.
  # We need to instantiate the empty `Plant` to provide it to the form.
  # check show.html.erb => our form is there
  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    # Retrieve the specific instance
    @plant = Plant.find(params[:id])
    # Destroy it from the database
    @plant.destroy

    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/show.html.erb
<%# BANNER %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container">
  <%# PLANTS  %>
  <div class="cards">
    <% @garden.plants.each do |plant| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>)">
        <%= plant.name %>
        <%# CHECK our _card.scss to see what we did with this '+' using the 'card-remove-link' class %>
        <%= link_to '+', plant_path(plant), method: 'DELETE', data: { confirm: 'Are you sure?' }, class: 'card-remove-link' %>
      </div>
    <% end %>
  </div>
  <%# NEW PLANT %>
  <div class="row justify-content-center">
    <div class="col-4 my-4">
      <div class="form-card">
        <h4>Add a plant:</h4>
        <%# Simple Form needs both instances to build the correct action as show in the next line %>
        <%# <form action='/garden/23(garden_id)/plants'> %>
        <%= simple_form_for([@garden, @plant]) do |f| %>
          <%= f.input :name, placeholder: 'Palm Tree' %>
          <%= f.input :image_url, placeholder: 'https://some_picture_from_google.png' %>
          <%= f.button :submit, class: 'my-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>